config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def new
    @article = Article.new
  end

  def index
    @articles = Article.all
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end


def destroy
  @article = Article.find(params[:id])
  @article.destroy

  redirect_to articles_path
end

  def show
     @article = Article.find(params[:id])
  end

  private
  def article_params
    params.require(:article).permit(:nama, :harga, :satuan)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <p>
    <%= form.label :nama %><br>
    <%= form.text_field :nama %>
  </p>

  <p>
    <%= form.label :harga %><br>
    <%= form.text_field :harga %>
  </p>

  <p>
    <%= form.label :satuan %><br>
    <%= form.text_field :satuan %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Barang</h1>


<%= render 'form' %>

<%= link_to 'Kembali', articles_path %>

app/views/articles/index.html.erb
<h1 style="color:red; text-align:center; margin-top:20px;">Daftar Harga Barang</h1>

<div class="container">

<a class="btn btn-primary" href="new" role="button">Tambah</a>

<table class="table table-bordered col-md-6">
  <thead>
    <tr style="text-align:center">
      <th>Barang</th>
      <th>Harga</th>
      <th>Satuan</th>
      <th colspan="3">Aksi</th>
    </tr>
  </thead>


  <%= @articles.each do |article| %>
  <tbody>
    <tr>
      <td><%= article.nama %></td>
      <td><%= article.harga %></td>
      <td><%= article.satuan %></td>
      <td><%= link_to 'show', article_path(article) %> |
      <%= link_to 'Edit', edit_article_path(article) %> |
      <%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  </tbody>


  <% end %>
</table>
</div>

app/views/articles/new.html.erb
<div class="container" style="margin-top:30px;">
  <h1>Harga Barang</h1>

  <%= render 'form' %>

  <%= link_to 'Kembali', articles_path %>

</div>

app/views/articles/show.html.erb
<div class="container" style="margin-top:30px;">
  <p>
    <strong>Nama Barang</strong>
    <%= @article.nama %>
  </p>

  <p>
    <strong>Harga Barang</strong>
    <%= @article.harga %>
  </p>

  <p>
    <strong>Satuan</strong>
    Rp.<%= @article.satuan %>
  </p>

  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Kembali', articles_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyfirst</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, rails</h1>

<%= link_to 'Harga Barang', controller: 'articles' %>